Pages/Materiales/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using AccesoriosArgentinos.Modelos;

namespace AccesoriosArgentinos._Pages_Materiales
{
    public class CreateModel : PageModel
    {
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;

        public CreateModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Material Material { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Materiales.Add(Material);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Materiales/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AccesoriosArgentinos.Modelos;

namespace AccesoriosArgentinos._Pages_Materiales
{
    public class DeleteModel : PageModel
    {
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;

        public DeleteModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Material Material { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Material = await _context.Materiales.FirstOrDefaultAsync(m => m.Id == id);

            if (Material == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Material = await _context.Materiales.FindAsync(id);

            if (Material != null)
            {
                _context.Materiales.Remove(Material);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Materiales/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AccesoriosArgentinos.Modelos;

namespace AccesoriosArgentinos._Pages_Materiales
{
    public class DetailsModel : PageModel
    {
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;

        public DetailsModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context)
        {
            _context = context;
        }

        public Material Material { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Material = await _context.Materiales.FirstOrDefaultAsync(m => m.Id == id);

            if (Material == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/Materiales/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AccesoriosArgentinos.Modelos;

namespace AccesoriosArgentinos._Pages_Materiales
{
    public class EditModel : PageModel
    {
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;

        public EditModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Material Material { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Material = await _context.Materiales.FirstOrDefaultAsync(m => m.Id == id);

            if (Material == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Material).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MaterialExists(Material.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool MaterialExists(int id)
        {
            return _context.Materiales.Any(e => e.Id == id);
        }
    }
}

Pages/Ordenes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using AccesoriosArgentinos.Modelos;

namespace AccesoriosArgentinos._Pages_Ordenes
{
    public class CreateModel : PageModel
    {
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;

        public CreateModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["InyectoraId"] = new SelectList(_context.Inyectoras, "Id", "Id");
            return Page();
        }

        [BindProperty]
        public OrdenesProduccionCabecera OrdenesProduccionCabecera { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.OrdenesProduccionCabeceras.Add(OrdenesProduccionCabecera);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Ordenes/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AccesoriosArgentinos.Modelos;

namespace AccesoriosArgentinos._Pages_Ordenes
{
    public class DeleteModel : PageModel
    {
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;

        public DeleteModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public OrdenesProduccionCabecera OrdenesProduccionCabecera { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            OrdenesProduccionCabecera = await _context.OrdenesProduccionCabeceras
                .Include(o => o.Inyectora).FirstOrDefaultAsync(m => m.Id == id);

            if (OrdenesProduccionCabecera == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            OrdenesProduccionCabecera = await _context.OrdenesProduccionCabeceras.FindAsync(id);

            if (OrdenesProduccionCabecera != null)
            {
                _context.OrdenesProduccionCabeceras.Remove(OrdenesProduccionCabecera);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Ordenes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AccesoriosArgentinos.Modelos;

namespace AccesoriosArgentinos._Pages_Ordenes
{
    public class DetailsModel : PageModel
    {
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;

        public DetailsModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context)
        {
            _context = context;
        }

        public OrdenesProduccionCabecera OrdenesProduccionCabecera { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            OrdenesProduccionCabecera = await _context.OrdenesProduccionCabeceras
                .Include(o => o.Inyectora).FirstOrDefaultAsync(m => m.Id == id);

            if (OrdenesProduccionCabecera == null)
            {
                return NotFound();
            }
            var Items = _context.OrdenesProduccionDetalles
                 .Include(x => x.Pieza)
                 .ThenInclude(x => x.Matriz)
                 .ThenInclude(x => x.Deposito)
                 .Include(x => x.Pieza)
                 .ThenInclude(x => x.MaterialPiezas)
                 .Where(x => x.OrdenProduccionCabeceraId == id)
                 .ToList();
            ViewData["Items"] = Items;
            return Page();
        }
    }
}

Pages/Ordenes/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AccesoriosArgentinos.Modelos;

namespace AccesoriosArgentinos._Pages_Ordenes
{
    public class EditModel : PageModel
    {
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;

        public EditModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public OrdenesProduccionCabecera OrdenesProduccionCabecera { get; set; }
         
         
        public IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewData["OrdenId"] = id; 
    
            LLenarPantalla((int)id);

            if (OrdenesProduccionCabecera == null)
            {
                return NotFound();
            }
            
            return Page();
        }

        public IActionResult OnPostPieza(int codigo,int cantidad) {
            //LLenarPantalla(OrdenesProduccionCabecera.Id);
            var valor1 = codigo;
            var valor2 = cantidad;
            var Pieza = _context.Piezas.Where(x => x.Id == codigo).First();

            var Item = new OrdenesProduccionDetalle();
            Item.Pieza = Pieza;
            Item.OrdenProduccionCabeceraId = OrdenesProduccionCabecera.Id;
            Item.Cantidad = cantidad;
            _context.OrdenesProduccionDetalles.Add(Item);
            _context.SaveChanges();
            return RedirectToPage("Edit", new { id = OrdenesProduccionCabecera.Id });


        }


        private void LLenarPantalla(int id)
        {
            /*
            var Items = _context.OrdenesProduccionDetalles
                        .Include(x => x.Pieza)
                        .ThenInclude(x => x.Material)
                        .Where(x => x.OrdenProduccionCabeceraId == id)
                        .ToList();
            */
            OrdenesProduccionCabecera = _context.OrdenesProduccionCabeceras
                            .Include(o => o.Inyectora) 
                            .Where(x => x.Id == id).First() ;
             
            var Items = _context.OrdenesProduccionDetalles 
                            .Include(x => x.Pieza)
                            .ThenInclude(x=>x.Matriz)
                            .ThenInclude(x=>x.Deposito)
                            .Include(x => x.Pieza)
                            .ThenInclude(x => x.MaterialPiezas)
                            .Where(x => x.OrdenProduccionCabeceraId == id)
                            .ToList();
           
  
            var Piezas = _context.Piezas.Where(x => x.InyectoraId == OrdenesProduccionCabecera.InyectoraId).ToList();
            ViewData["InyectoraId"] = new SelectList(_context.Inyectoras, "Id", "Id");
            ViewData["Items"] = Items;
            ViewData["Piezas"] = new SelectList(Piezas, "Id", "NombreCompleto");

        }


        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(OrdenesProduccionCabecera).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrdenesProduccionCabeceraExists(OrdenesProduccionCabecera.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
           
            return RedirectToPage("./Index");
        }

        private bool OrdenesProduccionCabeceraExists(int id)
        {
            return _context.OrdenesProduccionCabeceras.Any(e => e.Id == id);
        }

    }
}

Pages/Ordenes/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AccesoriosArgentinos.Modelos;

namespace AccesoriosArgentinos._Pages_Ordenes
{
    public class IndexModel : PageModel
    {
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;

        public IndexModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context)
        {
            _context = context;
        }

        public IList<OrdenesProduccionCabecera> OrdenesProduccionCabecera { get;set; }

        public async Task OnGetAsync()
        {
            OrdenesProduccionCabecera = await _context.OrdenesProduccionCabeceras
                .Include(o => o.Inyectora).ToListAsync();
        }
    }
}

Pages/Piezas/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using AccesoriosArgentinos.Modelos;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace AccesoriosArgentinos._Pages_Piezas
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public PiezaVM PiezaVM { get; set; }
        [BindProperty]
        public int MaterialId {get;set;}
        private readonly AccesoriosArgentinos.Modelos.AccesoriosDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        
        public CreateModel(AccesoriosArgentinos.Modelos.AccesoriosDbContext context,IWebHostEnvironment hostingEnviroment)
        {
            _context = context;
            _hostingEnvironment=hostingEnviroment;
        }

        public IActionResult OnGet()
        {
            PiezaVM = new PiezaVM();
            PiezaVM.Pieza = new Pieza();
            PiezaVM.ListaMarcas = new SelectList(_context.Marcas, "Id", "Descripcion");
            PiezaVM.ListaMateriales = new SelectList(_context.Materiales, "Id", "Descripcion");
            PiezaVM.ListaMatrices = new SelectList(_context.Matrices, "Id", "Descripcion");
            PiezaVM.ListaInyectoras = new SelectList(_context.Inyectoras, "Id", "Descripcion");
            return Page();
        }

   
        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if(PiezaVM.Pieza.Foto!=null){
                string carpetaFotos=Path.Combine(_hostingEnvironment.WebRootPath,"images");
                string nombreArchivo= PiezaVM.Pieza.Codigo + ".jpg";
                string rutaCompleta=Path.Combine(carpetaFotos,nombreArchivo);
                //subimos la imagen al servidor
                PiezaVM.Pieza.Foto.CopyTo(new FileStream(rutaCompleta,FileMode.Create));
                //guardar la ruta de la imagen en la base de datos
                PiezaVM.Pieza.FotoRuta=nombreArchivo;
            }
            _context.Piezas.Add(PiezaVM.Pieza);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Ordenes/Create.cshtml
@page
@model AccesoriosArgentinos._Pages_Ordenes.CreateModel

@{
    ViewData["SubTitle"] = "Crear";
    ViewData["Title"] = "Orden";
}
<div class="row">
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0">
                <h4>Crear Orden de compra</h4>
                <a asp-page="Create" class="btn btn-outline-secondary btn-sm mb-0 me-3">Crear Orden</a>
            </div>
            <div class="card-body px-0 pt-0 pb-2">

                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="OrdenesProduccionCabecera.InyectoraId" class="control-label"></label>
                        <select asp-for="OrdenesProduccionCabecera.InyectoraId" class="form-control" asp-items="ViewBag.InyectoraId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="OrdenesProduccionCabecera.FechaCreacion" class="control-label"></label>
                        <input asp-for="OrdenesProduccionCabecera.FechaCreacion" class="form-control" />
                        <span asp-validation-for="OrdenesProduccionCabecera.FechaCreacion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Crear" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div>
                <a asp-page="Index">Volver</a>
            </div>
        </div>
    </div>
</div>

Pages/Ordenes/Delete.cshtml
@page
@model AccesoriosArgentinos._Pages_Ordenes.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrdenesProduccionCabecera</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrdenesProduccionCabecera.FechaCreacion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrdenesProduccionCabecera.FechaCreacion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrdenesProduccionCabecera.Inyectora)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrdenesProduccionCabecera.Inyectora.Id)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="OrdenesProduccionCabecera.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Volver</a>
    </form>
</div>

Pages/Ordenes/Edit.cshtml
@page
@model AccesoriosArgentinos._Pages_Ordenes.EditModel

@{
    ViewData["SubTitle"] = "Editar";
    ViewData["Title"] = "Ordenes";
}
<div class="row">
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0">
                <h4>Ordenes Produccion Cabecera</h4>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
                <div class="row">
                    <form method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="OrdenesProduccionCabecera.Id" />

                        <div style="padding: 10px;" class="row">
                            <div class="form-group col-md-6">
                                <label asp-for="OrdenesProduccionCabecera.InyectoraId"></label>
                                @Html.DisplayFor(model => model.OrdenesProduccionCabecera.Inyectora.Id, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="OrdenesProduccionCabecera.FechaCreacion"></label>
                                @Html.DisplayFor(model => model.OrdenesProduccionCabecera.FechaCreacion, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        </div>


                        <div style="margin: 15px; padding: 10px; border-radius: 20px; border: 1px solid" class="row">
                            <input type="hidden" id="hfPersonId" name="OrdenId" asp-for="OrdenesProduccionCabecera.Id" />
                            <div class="col-sm-6">
                                <label class="control-label">Pieza</label>
                                <div>
                                    <select name="codigo" class="form-control" asp-items="ViewBag.Piezas"></select>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <label class="control-label">Cantidad</label>
                                <div>
                                    <input name="cantidad" class="form-control" />
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <input type="submit" value="Guardar" class="btn btn-primary" asp-page-handler="Pieza" />
                            </div>
                        </div>

                    </form>
                </div>
                <table class="table align-items-center mb-0">
                    <thead>
                        <tr>
                            <th>
                                Pieza
                            </th>
                            <th>
                                Matriz
                            </th>
                            <th class="text-center">
                                Cantidad
                            </th>
                            <th>Material</th>
                            <th class="text-center">Peso Total</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in (IEnumerable<AccesoriosArgentinos.Modelos.OrdenesProduccionDetalle>)ViewData["Items"])
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Pieza.Descripcion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Pieza.MatrizId)
                                    <b>(@Html.DisplayFor(modelItem => item.Pieza.Matriz.Deposito.DescripcionCorta))</b>
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Cantidad)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Pieza.MaterialPiezas.First().Material.Descripcion)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.PesoTotal)
                                </td>
                                <td class="text-center">
                                    <a asp-page="./Delete" asp-route-id="@item.PiezaId">
                                        <i class="far fa-trash-alt me-2" aria-hidden="true"></i> 
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <div>
                    <a class="btn btn-outline-secondary" asp-page="./Index">Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.6/jspdf.plugin.autotable.min.js"></script>
    <script>
        function ImprimirPDF() {
            var pdf = new jsPDF('p', 'pt', 'letter');
            
            // all coords and widths are in jsPDF instance's declared units
            // 'inches' in this case
            /*
            // source can be HTML-formatted string, or a reference
            // to an actual DOM element from which the text will be scraped.
            source = $('table')[0];

            // we support special element handlers. Register them with jQuery-style
            // ID selector for either ID or node name. ("#iAmID", "div", "span" etc.)
            // There is no support for any other type of selectors
            // (class, of compound) at this time.
            specialElementHandlers = {
                // element with id of "bypass" - jQuery style selector
                '#bypassme': function (element, renderer) {
                    // true = "handled elsewhere, bypass text extraction"
                    return true
                }
            };
            margins = {
                top: 80,
                bottom: 60,
                left: 40,
                width: 522
            };
            pdf.fromHTML(
                source, // HTML string or DOM elem ref.
                margins.left, // x coord
                margins.top, { // y coord
                'width': margins.width, // max width of content on PDF
                'elementHandlers': specialElementHandlers
            },
                          function (dispose) {
                    // dispose: object with X, Y of the last line add to the PDF
                    //          this allow the insertion of new lines after html
                    pdf.save('Test.pdf');
                }, margins);
            */
            pdf.autoTable({
                html: 'table',
                startY: 70,
                theme: 'grid',
                columnStyles: {
                    0: {
                        cellWidth: 200,
                    },
                    1: {
                        cellWidth: 50,
                    },
                    2: {
                        cellWidth: 60,
                    },
                    3: {
                        cellWidth: 130,
                    },
                    4: {
                        cellWidth: 0,
                    },
                },
                styles: {
                    minCellHeight: 20
                }
            });
            pdf.save('OrdenDeCompra.pdf');


        }
    </script>
} 

Pages/Ordenes/Index.cshtml
@page
@model AccesoriosArgentinos._Pages_Ordenes.IndexModel

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0">
                <h4>Ordenes de compra</h4>
                <a asp-page="Create" class="btn btn-outline-secondary btn-sm mb-0 me-3">Crear Orden</a>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.OrdenesProduccionCabecera[0].FechaCreacion)
                            </th>
                            <th class="text-center">
                                @Html.DisplayNameFor(model => model.OrdenesProduccionCabecera[0].Inyectora)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.OrdenesProduccionCabecera)
                        {
                            <tr>
                                <td>
                                    <i class="far fa-calendar-alt me-2" aria-hidden="true"></i>
                                    @Html.DisplayFor(modelItem => item.FechaCreacion)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Inyectora.Id)
                                </td>
                                <td class="text-center">
                                    <a asp-page="./Edit" asp-route-id="@item.Id">
                                        <i class="fas fa-pencil-alt text-dark me-2" aria-hidden="true"></i>Editar
                                    </a> |
                                    <a asp-page="./Delete" asp-route-id="@item.Id">
                                        <i class="far fa-trash-alt me-2" aria-hidden="true"></i> Borrar
                                    </a>|
                                    <a asp-page="./Details" asp-route-id="@item.Id">
                                        <i class="fas fa-file-pdf text-lg me-1" aria-hidden="true"></i>Imprimir
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>